### ISSUE TITLE
hackerHot gravity error means score returns as NaN

### ISSUE THREAD

**Issue by awidgery** [clux/decay#3]
I'm following exactly the code in the Readme:

    var hackerHotScore = decay.hackerHot(decay);
    var score = hackerHotScore(upVotes, date);

But `score` is returning as `NaN`.

I've debugged it and in `exports.hackerHot = function (gravity) {}` in the `return function(votes, itemDate)` if I `console.log(gravity);` I get:

    { redditHot: [Function],
      hackerHot: [Function],
      wilsonScore: [Function] }

This means that `Math.pow(hourAge + 2, gravity)` returns `NaN`.

If I hardcode the 1.8 gravity parameter in (`Math.pow(hourAge + 2, 1.8)`) then the score is returned correctly.

Am I doing something wrong, or is this a bug?

**Comment by clux** [comment]
Well, you are passing `decay` as the `gravity` parameter to `decay.hackerHot` in the first line.
Try passing a number :)

**Comment by clux** [comment]
Oh wow. That is actually wrong in the readme. Yeah, sorry. That has been wrong for ages wtf.

**Comment by clux** [comment]
Thanks for the issue, other people have probably seen this and had to investigate in some way.

**Comment by awidgery** [comment]
Yeah - though I still should have spotted the readme mistake! Thanks for superfast response!
