### ISSUE TITLE
Post date

### ISSUE THREAD

**Issue by ieshan** [clux/decay#7]
In the wilsonScore example on your readme.md you have a time parameter

```
req.entry.score = wilsonScore(req.entry.upVotes + 1, req.entry.dnVotes, req.entry.postDate);
```
But in the function it doesn't consider time.
https://github.com/clux/decay/blob/7227b8ef600e298ab4330f9abd1fccda69c9c78b/decay.js#L50

Is there a way to consider the post time?

**Comment by clux** [comment]
Ah, that's a mistake, thanks. `wilsonScore` by definition, does not take into account date. If you want that, you want one of the decaying algorithms instead.
